/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as OnboardingInviteRouteImport } from './routes/onboarding/invite'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppWSlugIndexRouteImport } from './routes/_app/w/$slug/index'
import { Route as AppWSlugMembersRouteImport } from './routes/_app/w/$slug/members'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppWSlugIndexRoute = AppWSlugIndexRouteImport.update({
  id: '/w/$slug/',
  path: '/w/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppWSlugMembersRoute = AppWSlugMembersRouteImport.update({
  id: '/w/$slug/members',
  path: '/w/$slug/members',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/w/$slug/members': typeof AppWSlugMembersRoute
  '/w/$slug/': typeof AppWSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/w/$slug/members': typeof AppWSlugMembersRoute
  '/w/$slug': typeof AppWSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/w/$slug/members': typeof AppWSlugMembersRoute
  '/_app/w/$slug/': typeof AppWSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/w/$slug/members'
    | '/w/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/w/$slug/members'
    | '/w/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_auth/login'
    | '/invite/$token'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/_app/'
    | '/_app/w/$slug/members'
    | '/_app/w/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/w/$slug/': {
      id: '/_app/w/$slug/'
      path: '/w/$slug'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof AppWSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$slug/members': {
      id: '/_app/w/$slug/members'
      path: '/w/$slug/members'
      fullPath: '/w/$slug/members'
      preLoaderRoute: typeof AppWSlugMembersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWSlugMembersRoute: typeof AppWSlugMembersRoute
  AppWSlugIndexRoute: typeof AppWSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWSlugMembersRoute: AppWSlugMembersRoute,
  AppWSlugIndexRoute: AppWSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
